### ISSUE TITLE
infinite or missing values in 'x'

### ISSUE THREAD

**Issue by Zepeng-Mu** [stephenslab/gtexresults#7] opened 2019-07-04 17:44 UTC
Hi,

Thanks for the great workflow.
I am running the `mashr_flashr_workflow` and got this error:

```
Loading required package: ashr
Fitting factor/loading 1 (stop when max factor change is < 1.00e-03):
Error in svd(t(B)) : infinite or missing values in 'x'
Calls: cov_flash ... flash_init_fn -> do.call -> my_init_fn -> <Anonymous>
Execution halted
```

This error only occurs when I use the "EZ" mode, but not with "EE" mode. Since I prepared my data with the default setting in `fastql_to_mashr` workflow, I am wondering what is the best way to solve this problem if I want to use "EE" mode.

Thanks!

**Comment by gaow** [comment] 2019-07-04 18:47
Hmm do you think you could share me the data via slack for me to take a look at @Zepeng-Mu ? Thanks!

**Comment by Zepeng-Mu** [comment] 2019-07-10 16:26
Hi, I think the error message is due to how std(beta) is calculated. I am using the workflow to calculate std previously because FastQTL by does not output it.
The reason seems to be that FastQTL reports all genes, even there is no SNP around them to be tested. So, in the output, there are many genes with "NA" values. These NA values cannot be properly treated in Python, because python codes them as "nan".

Now I am calculating std and converting "NA" to "-nan" in R before running the workflow, and there is no error message for now.

Thanks!

**Comment by gaow** [comment] 2019-07-10 16:34
@Zepeng-Mu sorry I'm still a bit confused here. If there are `NA` values the way you described, then they should also present in `beta` right? In the end you get a matrix with rows being gene-snp pairs and columns tissues, but for some of the rows all values are `nan` (as a result of Python?)? It would then seem reasonable that we post process the generated matrix removing such rows -- am I understanding it right?

**Comment by Zepeng-Mu** [comment] 2019-07-10 16:54
In some rows, the beta and P would be NA, then the calculated std should also be NA.
I am only guessing that the "NA" in my input cannot be recognized by Python, because it seems that python uses "NaN" or "nan" to present missing values.

But I agree that it is better to remove those rows from the output matrix. For now I am not doing that, and I am not sure how python handles those NA values.

**Comment by gaow** [comment] 2019-07-11 18:45
On a second thought I'll not change the converter pipeline code (Python) because the converter should do a faithful job representing the input data, even though imperfectly (use nan for missing values). But I'll change the mash data extractor to ensure it does not happen because that extractor should prepare data suitable for the next mash pipeline. I'll try to make a test dataset to reproduce then fix it ...

**Comment by Zepeng-Mu** [comment] 2019-07-11 21:10
Sorry that I was not clear enough.

The FastQTL output contains "NA", but in python `float('NA')` returns `ValueError: could not convert string to float: 'NA'`.
However, `float('NaN')` and `float('nan')` returns `nan`.
So I am wondering whether I should code NA as "NaN" before using python to process the data. I am only guessing this might matter but I could be wrong.

I agree that it is OK to leave 'nan' in the data as missing values.

**Comment by gaow** [comment] 2019-07-12 17:17
@Zepeng-Mu thanks for sharing the test data. It boils down to `mash_set_data` function:

https://github.com/stephenslab/mashr/blob/master/R/set_data.R#L77

this line properly fixes problem in `se(bhat)` but will cause `inf` in `Bhat`. Later we indeed took care of `nan` Bhat but not `inf`:

https://github.com/stephenslab/mashr/blob/master/R/set_data.R#L89

@pcarbo @stephens999 should we change 

```
  Bhat[which(is.nan(Bhat))] = 0
```

to 

```
Bhat[which(is.nan(Shat) | is.infinite(Shat))] = 0
```

in `mash_set_data` function?

**Comment by gaow** [comment] 2020-04-16 02:56
I believe this issue has been resolved in `mashr` now.

**Closed by gaow** 2020-04-16 02:56 UTC
